pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/CesarRodriguezPardo/tingeso_lab1']])
                dir("front"){
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("front"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            sh "docker build --platform=linux/amd64 -t cesarrodriguezpardo/prestabanco-frontend:latest ."
                            sh "docker push cesarrodriguezpardo/prestabanco-frontend:latest"
                        }
                    }                    
                }
            }
        }
    }
}